### ISSUE TITLE
I think there's a critical typo

### ISSUE THREAD

**Issue by Andygurl5566** [learn-co-curriculum/phase-0-pac-1-programming-with-expressions#1]
Thanks for raising this issue! Future learners thank you for your diligence. In
order to help the curriculum team address the problem, please use this template
to submit your feedback. We'll work on addressing the issue as soon as we can.

Please fill out as much of the information below as you can (it's ok if you
don't fill out every section). The more context we have, the easier it will be
to fix your issue!

_**Note**: you should only raise issues related to the contents of this lesson.
If you have questions about your code or need help troubleshooting, reach out to
an instructor/your peers._

---

## Link to Canvas
https://learning.flatironschool.com/courses/4711/pages/programming-with-expressions?module_item_id=282188

> Add a link to the assignment in Canvas here.

## What should be changed?
If the expression in the first position evaluates to a truthy value, then the return value of the ternary expression is whatever is in the **second position**; here, "thingToReturnIfTrue"

> Suggest your change here. Let us know what section or line of the Readme needs
> to be updated, and any proposed corrections. Include the line number(s) if
> possible.
If the expression in the first position evaluates to a truthy value, then the return value of the ternary expression is whatever is in the **first position**; here, "thingToReturnIfTrue"

## Additional context
This line is located under the Identify the Ternary Expression 

> Add any other context about the problem here.

**Comment by ihollander** [comment]
Hi @Andygurl5566 - thanks for reaching out about this! To clarify, the ternary expression has three positions:

```js
firstPosition ? secondPosition : thirdPosition
```

In the sentence you're referencing, "second position" refers to the item after the question mark (?) and "first position" refers to the item before the question mark. So the original description of the ternary expression is correct here, since whatever is in the second position will be returned when the first position is a truthy value.
