### ISSUE TITLE
Wrong syntax in example

### ISSUE THREAD

**Issue by yahwehschica7** [learn-co-curriculum/phase-0-pac-1-programming-with-expressions#2]
Thanks for raising this issue! Future learners thank you for your diligence. In
order to help the curriculum team address the problem, please use this template
to submit your feedback. We'll work on addressing the issue as soon as we can.

Please fill out as much of the information below as you can (it's ok if you
don't fill out every section). The more context we have, the easier it will be
to fix your issue!

_**Note**: you should only raise issues related to the contents of this lesson.
If you have questions about your code or need help troubleshooting, reach out to
an instructor/your peers._

---

## Link to Canvas

>https://learning.flatironschool.com/courses/4409/pages/programming-with-expressions?module_item_id=271507

## Describe the bug
In the section:
Write a Program with Conditional Logic Using Expressions
Someone accidentally used curly braces instead of parentheses in the example replit code (last line of it when citing temperature and using booleans). I got an error in replit but saw the discrepancy. Not sure if it's something you'll want to fix.

**Comment by ihollander** [comment]
Hi @yahwehschica7 - thanks for raising this issue! Upon review, I'm not able to see the same syntax error you've mentioned. Here is what the code should look like in the first repl.it example in that section:

```js
//Input values: we could easily imagine asking a user for these values.
const name = "Your name here";
const rainPercentage = 0.2;
const temperatureInC = 26;

`Hello, ${name}, with a rain chance of ${rainPercentage * 100}% and a temperature of ${temperatureInC}C we recommend that you ` + (rainPercentage > 0.3 ? "take an umbrella" : "enjoy this rain-free day") +
`${temperatureInC >= 26 ? ' and watch out for heatstroke.' : ' and bask in this fine weather.'}`;
```

Pressing the play button to execute this code in the repl produces following the output:

```txt
Hello, Your name here, with a rain chance of 20% and a temperature of 26C we recommend that you enjoy this rain-free day and watch out for heatstroke.
```

The second repl in that section with the cleaned-up code produces the same output:

```js
const probabilityOfRain = 0.2;
const temperatureInC = 26;

const likelyToRain = probabilityOfRain > 0.3;
const sunIsDangerous = temperatureInC >= 26;

const rainPercentage = probabilityOfRain * 100;
const rainAdvice = likelyToRain ? "take an umbrella" : "enjoy this rain-free day";
const sunAdvice = sunIsDangerous ? "watch out for heatstroke" : "bask in this fine weather";

`Hello, ${name}, with a rain chance of ${rainPercentage}% and a temperature of ${temperatureInC}C we recommend that you ${rainAdvice} and ${sunAdvice}.`;
```

The first example is definitely more difficult to read, and that's intentional - we wanted to show the process of refactoring code from something that works, but isn't easy to understand, to something that both works **and** is easier to understand.
